redis:
  addr: 172.24.0.3:6379
  password: ""
  db: 0
  flushOnStart: true

postgresql:
  # connect_timeout ./vendor/github.com/lib/pq/doc.go in seconds
  # statement_timeout https://postgrespro.ru/docs/postgrespro/9.6/runtime-config-client in milliseconds
  connectString: "host=172.24.0.2 user=postgres password=postgresqlPassword dbname=postgres connect_timeout=2 statement_timeout=2000 sslmode=disable"