redis:
  addr: 172.24.0.3:6379
  password: ""
  db: 0
  flushOnStart: true

postgresql:
  # connect_timeout ./vendor/github.com/lib/pq/doc.go in seconds
  # statement_timeout https://postgrespro.ru/docs/postgrespro/9.6/runtime-config-client in milliseconds
  connectString: "host=172.24.0.2 user=postgres password=postgresqlPassword dbname=postgres connect_timeout=2 statement_timeout=2000 sslmode=disable"
  maxOpenConnections: 8
  maxIdleConnections: 2
  dropObjects: true
  dropObjectsSql: |
    DROP SCHEMA public CASCADE;
    CREATE SCHEMA public;

    GRANT ALL ON SCHEMA public TO postgres;
    GRANT ALL ON SCHEMA public TO public;

    COMMENT ON SCHEMA public IS 'standard public schema';


mail:
  registration:
    fromAddress: "from@yandex.ru"
    subject: "registration confirmation"
    body.template: "Go to link for complete your registration __link__"
  smtp:
    address: "smtp.yandex.ru:465"
    username: "username"
    password: "password"

url: "http://localhost:1234" # without trailing slash
# localhost need for facebook

confirmation.token.ttl: "20m"
session.ttl: "30m"

facebook:
  clientId: "1684113965162824"
  clientSecret: "provide it"