
[[constraint]]
  name = "github.com/Boostport/migration"
  version = "0.10.0"

[[constraint]]
  name = "gopkg.in/DATA-DOG/go-sqlmock.v1"
  version = "1.3.0"

[[constraint]]
  name = "github.com/labstack/echo"
  version = "3.3.5"

[[constraint]]
  name = "github.com/go-redis/redis"
  version = "6.12.0"

[[constraint]]
  name = "github.com/satori/go.uuid"
  version = "1.2.0"
