
[[constraint]]
  name = "github.com/Boostport/migration"
  version = "0.10.0"

[[constraint]]
  name = "gopkg.in/DATA-DOG/go-sqlmock.v1"
  version = "1.3.0"

[[constraint]]
  name = "github.com/labstack/echo"
  version = "3.3.5"

[[constraint]]
  branch = "v2_renamed"
  name = "github.com/nkonev/authboss"
