
[[constraint]]
  name = "github.com/Boostport/migration"
  version = "0.10.0"

[[constraint]]
  name = "gopkg.in/DATA-DOG/go-sqlmock.v1"
  version = "1.3.0"

[[constraint]]
  name = "github.com/labstack/echo"
  version = "3.3.5"

[[constraint]]
  name = "github.com/volatiletech/authboss"
  version = "v2.0.0-rc5"
