
[[constraint]]
  name = "github.com/Boostport/migration"
  version = "0.11.0"

[[constraint]]
  name = "gopkg.in/DATA-DOG/go-sqlmock.v1"
  version = "1.3.0"

[[constraint]]
  name = "github.com/labstack/echo"
  version = "3.3.5"

[[constraint]]
  name = "github.com/go-redis/redis"
  version = "6.12.0"

[[constraint]]
  name = "github.com/satori/go.uuid"
  version = "1.2.0"

[[constraint]]
  name = "github.com/spf13/viper"
  version = "1.0.2"

[[constraint]]
  name = "github.com/gobuffalo/packr"
  version = "1.12.0"

[[constraint]]
  name = "mvdan.cc/xurls"
  version = "1.1.0"

[[constraint]]
  branch = "master"
  name = "golang.org/x/oauth2"

[[constraint]]
  name = "github.com/huandu/facebook"
  version = "2.3.0"

[[constraint]]
  name = "go.uber.org/dig"
  version = "1.4.0"

[[constraint]]
  name = "github.com/guregu/null"
  version = "3.4.0"
